receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317  # OTLP gRPC endpoint
      http:
        endpoint: 0.0.0.0:4318  # OTLP HTTP endpoint

exporters:
  otlp:
    endpoint: "jaeger:4317"  # Jaeger OTLP gRPC receiver endpoint
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:9464
    namespace: default

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
